// GENERATED from design/DESIGN.md frontmatter by web/build/gen-tokens.mjs.
// Do not edit: change DESIGN.md and run `npm run tokens`. A vitest test
// fails if this file and the frontmatter disagree.

import * as stylex from '@stylexjs/stylex';

export const colors = stylex.defineVars({
  surface: "#0f131c",
  surfaceDim: "#0f131c",
  surfaceBright: "#353943",
  surfaceContainerLowest: "#0a0e17",
  surfaceContainerLow: "#181c25",
  surfaceContainer: "#1c2029",
  surfaceContainerHigh: "#262a34",
  surfaceContainerHighest: "#31353f",
  onSurface: "#dfe2ef",
  onSurfaceVariant: "#b9cbb9",
  inverseSurface: "#dfe2ef",
  inverseOnSurface: "#2c303a",
  outline: "#849585",
  outlineVariant: "#3b4b3d",
  surfaceTint: "#00e479",
  primary: "#f1ffef",
  onPrimary: "#003919",
  primaryContainer: "#00ff88",
  onPrimaryContainer: "#007139",
  inversePrimary: "#006d37",
  secondary: "#ffb2ba",
  onSecondary: "#670020",
  secondaryContainer: "#d4004b",
  onSecondaryContainer: "#ffe6e8",
  tertiary: "#eefeff",
  onTertiary: "#00363a",
  tertiaryContainer: "#5cf2ff",
  onTertiaryContainer: "#006d74",
  error: "#ffb4ab",
  onError: "#690005",
  errorContainer: "#93000a",
  onErrorContainer: "#ffdad6",
  primaryFixed: "#60ff99",
  primaryFixedDim: "#00e479",
  onPrimaryFixed: "#00210c",
  onPrimaryFixedVariant: "#005228",
  secondaryFixed: "#ffd9dc",
  secondaryFixedDim: "#ffb2ba",
  onSecondaryFixed: "#400011",
  onSecondaryFixedVariant: "#910030",
  tertiaryFixed: "#7df4ff",
  tertiaryFixedDim: "#00dbe9",
  onTertiaryFixed: "#002022",
  onTertiaryFixedVariant: "#004f54",
  background: "#0f131c",
  onBackground: "#dfe2ef",
  surfaceVariant: "#31353f",
});

export const radius = stylex.defineVars({
  sm: "0.125rem",
  base: "0.25rem",
  md: "0.375rem",
  lg: "0.5rem",
  xl: "0.75rem",
  full: "9999px",
});

export const space = stylex.defineVars({
  gutter: "0.75rem",
  margin: "1rem",
  spaceXs: "0.25rem",
  spaceSm: "0.5rem",
  spaceMd: "0.75rem",
  spaceLg: "1.25rem",
  spaceXl: "2rem",
});

export const type = stylex.defineVars({
  headlineXlFamily: "'Syne', 'Futura', 'Avenir Next', system-ui, sans-serif",
  headlineXlSize: "36px",
  headlineXlWeight: "800",
  headlineXlLine: "42px",
  headlineXlTracking: "-0.04em",
  headlineXlMobileFamily: "'Syne', 'Futura', 'Avenir Next', system-ui, sans-serif",
  headlineXlMobileSize: "28px",
  headlineXlMobileWeight: "800",
  headlineXlMobileLine: "34px",
  headlineXlMobileTracking: "-0.03em",
  headlineLgFamily: "'Syne', 'Futura', 'Avenir Next', system-ui, sans-serif",
  headlineLgSize: "26px",
  headlineLgWeight: "700",
  headlineLgLine: "32px",
  headlineLgTracking: "-0.02em",
  headlineSmFamily: "'Syne', 'Futura', 'Avenir Next', system-ui, sans-serif",
  headlineSmSize: "18px",
  headlineSmWeight: "700",
  headlineSmLine: "24px",
  headlineSmTracking: "0em",
  titleMdFamily: "'JetBrains Mono', ui-monospace, SFMono-Regular, 'Cascadia Mono', Consolas, monospace",
  titleMdSize: "15px",
  titleMdWeight: "600",
  titleMdLine: "20px",
  titleMdTracking: "-0.01em",
  bodyLgFamily: "'JetBrains Mono', ui-monospace, SFMono-Regular, 'Cascadia Mono', Consolas, monospace",
  bodyLgSize: "14px",
  bodyLgWeight: "400",
  bodyLgLine: "22px",
  bodyLgTracking: "-0.01em",
  bodySmFamily: "'JetBrains Mono', ui-monospace, SFMono-Regular, 'Cascadia Mono', Consolas, monospace",
  bodySmSize: "12px",
  bodySmWeight: "400",
  bodySmLine: "18px",
  bodySmTracking: "0em",
  labelMdFamily: "'JetBrains Mono', ui-monospace, SFMono-Regular, 'Cascadia Mono', Consolas, monospace",
  labelMdSize: "11px",
  labelMdWeight: "500",
  labelMdLine: "14px",
  labelMdTracking: "0.06em",
  labelXsFamily: "'JetBrains Mono', ui-monospace, SFMono-Regular, 'Cascadia Mono', Consolas, monospace",
  labelXsSize: "9px",
  labelXsWeight: "700",
  labelXsLine: "12px",
  labelXsTracking: "0.12em",
});
