#!/usr/bin/env python
"""A PACKAGE'S EXAMPLES at the pinned commit: human-written code, screened as
data, labelled by its OWN imports.

    python mcp/package_examples.py show <onboarding id>    examples.json

docs/PACKAGE-ONBOARDING.md 6.1-6.2 (the onboarding's `examples` stage, item
H). Operator: "r3f's examples are mostly drei; TypeGPU, Koota and drei have
many" -- so every file is labelled by what IT imports (multi-package rows),
never by the repository it came from.

DISCOVERY, at the resolved commit, from the tree listing package_sources
reads (one recursive tree, recorded): the directories the PROMPT links come
first (package_sources.discover's `examples_dirs`, else the resolution's
linked folders), then every directory whose name marks examples
(EXAMPLE_DIRS: the design's starting CONVENTION, to be checked against the
repositories of the packages we hold -- a docs app's `examples` folder under
docs/ or apps/* is matched by the same name). The outermost such directory
is the ROOT. The listing's top-level directories and the roots chosen are
recorded, so a miss is visible.

THE GROUP (the unit every later split and vote uses; operator decision 1,
2026-09-27: leave-one-GROUP-out, no held-out fraction): the directory
directly under a root for a multi-file demo, else the file.

FILTERS (6.1), each drop recorded with its reason and counted:
  node_modules       a dependency's files, anywhere in the path
  built_dir          a folder below the root named in deps.BUILT_DIRS
  lockfile           package-lock.json, yarn.lock, pnpm-lock.yaml, ...
  extension          not .ts .tsx .js .jsx .mjs (counted per extension)
  minified           `.min.` in the name, or deps.is_minified on the text
  too_large          over deps.MAX_FILE_BYTES (the per-file cap
                     index_code.iter_files already applies; operator
                     decision 9: no cap of ours)
  unsafe_path        a path that cannot be stored under the store root
  blob_mismatch      the bytes fetched are not the tree's blob (git's own
                     sha1 over "blob <n>\\0" + bytes)
  binary / not_utf8  a NUL byte, or not UTF-8 text
  generated          the file's leading comment says the FILE was generated
                     (@generated, auto-generated, "this file was
                     generated", "Code generated by"); a demo describing
                     what its code generates is kept
  hidden_characters  skill_screen's invisible characters that remain after
                     its zero-width typography is stripped (tag characters,
                     bidi controls, ...): the skill screen QUARANTINES them,
                     an example file is dropped
  credential         skill_screen's credential rule -- the patterns it
                     applies to code (a live-looking secret, reading a key
                     file, printing a secret); its two REQUEST patterns read
                     prose only, as in the screen
  duplicate          deps._dedupe's rule (the same file twice, or a CJS /
                     UMD copy of an ESM file)

FETCHING: GET only, one file at a time at the commit (package_net.raw), the
per-file cap passed as max_bytes; a file whose blob sha is already stored is
not fetched again (a per-commit `.blobs.json` records each blob's verdict
under RULES_VERSION). Stored TEXT ONLY, under YAMADORI_EXAMPLES_DIR (default
<repo>/index/packages/_examples)/<deps.slug(name, version)>/<commit>/<path>.
Example text never reaches a model's prompt: it is embedded and stored.

OUTPUTS under onboarding.out_dir(did): examples.json (the summary) and
examples/manifest.jsonl (one row per kept file).
"""
from __future__ import annotations

import collections
import hashlib
import json
import os
import re
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# The design's starting convention (docs/PACKAGE-ONBOARDING.md 6.1).
EXAMPLE_DIRS = ("example", "examples", "demo", "demos", "sandbox",
                "sandboxes", "stories")
# The JS/TS family deps.imported reads (6.1).
EXTS = (".ts", ".tsx", ".js", ".jsx", ".mjs")
LOCKFILES = ("package-lock.json", "npm-shrinkwrap.json", "yarn.lock",
             "pnpm-lock.yaml", "bun.lockb", "bun.lock")
# Bumped whenever a filter or a label rule changes: a stored blob verdict
# made under another version is not reused.
RULES_VERSION = "examples/1"
MANIFEST = os.path.join("examples", "manifest.jsonl")
SUMMARY = "examples.json"
BLOBS = ".blobs.json"

# A header that says the FILE was generated -- not a demo describing what
# its code generates ("terrain generated from noise" is kept).
_GENERATED = re.compile(
    r"(?i)@generated\b|\bauto-?generated\b"
    r"|\b(?:file|code)\s+(?:(?:is|was|has\s+been)\s+)?(?:automatically\s+)?"
    r"generated\b")
_LEADING_COMMENT = re.compile(r"\A(?:\s*(?://[^\n]*|/\*.*?\*/|#![^\n]*))+",
                              re.S)
_ID = re.compile(r"[A-Za-z_$][\w$]*")
_NPM_NAME = re.compile(r"(?:@[a-z0-9][\w.-]*/)?[a-z0-9][\w.-]*")

# The statements that carry a file's labels, removed from what is indexed
# and from what the evaluation reads (6.2: "a vector that saw them would
# learn the label from its own answer"). Replaced by as many newlines as
# they spanned, so line numbers hold.
_STRIP = [
    re.compile(r"""^[ \t]*import\s+(?:type\s+)?[^'";]*?\s+from\s*['"][^'"\n]+"""
               r"""['"][ \t]*(?:with\s*\{[^}]*\}[ \t]*)?;?""", re.M | re.S),
    re.compile(r"""^[ \t]*import\s*['"][^'"\n]+['"][ \t]*;?""", re.M),
    re.compile(r"""^[ \t]*export\s+(?:type\s+)?(?:\*(?:\s*as\s+[\w$]+)?|"""
               r"""\{[^}]*\})\s*from\s*['"][^'"\n]+['"][ \t]*;?""",
               re.M | re.S),
    re.compile(r"""^[ \t]*(?:const|let|var)\s+(?:\{[^}]*\}|[A-Za-z_$][\w$]*)"""
               r"""\s*=\s*require\s*\(\s*['"][^'"\n]+['"]\s*\)[ \t]*;?""",
               re.M | re.S),
    re.compile(r"""^[ \t]*require\s*\(\s*['"][^'"\n]+['"]\s*\)[ \t]*;?""",
               re.M),
]
# A dynamic import's specifier is the same label source: blanked in place.
_DYNAMIC = re.compile(r"""\bimport\s*\(\s*['"][^'"\n]+['"]\s*\)""")
_SPEC = re.compile(
    r"""(?:\bfrom\s*|\bimport\s*\(?\s*|\brequire\s*\(\s*)['"]([^'"\s]+)['"]""")


def _deps():
    import deps
    return deps


def store_root() -> str:
    d = os.environ.get("YAMADORI_EXAMPLES_DIR")
    if d:
        return os.path.abspath(d)
    return os.path.join(os.path.abspath(_deps().STORE), "_examples")


def store_dir(name: str, version: str, commit: str) -> str:
    return os.path.join(store_root(), _deps().slug(name, version), commit)


def git_blob_sha(data: bytes) -> str:
    """git's blob id: sha1 over "blob <len>\\0" + bytes (what a tree lists)."""
    h = hashlib.sha1()
    h.update(b"blob %d\0" % len(data))
    h.update(data)
    return h.hexdigest()


def group_hash(repository: str, group: str) -> str:
    """The group's id: its repository and its path, NOT its commit -- the
    same demo at two versions is one group, so a held-out group is never
    voted for by its own earlier copy."""
    return hashlib.sha256(f"{repository.lower()}:{group}".encode(
        "utf-8")).hexdigest()[:16]


def file_id(repository: str, path: str, blob: str) -> str:
    return hashlib.sha256(f"{repository.lower()}:{path}:{blob}".encode(
        "utf-8")).hexdigest()[:16]


# ---------------------------------------------------------------------------
# Text rules (shared with example_knn and package_eval).
# ---------------------------------------------------------------------------
def strip_imports(text: str) -> str:
    """The text with every import / require / re-export statement removed
    (line count kept) and each dynamic import's specifier blanked."""
    def blank(m):
        return "\n" * m.group(0).count("\n")
    for rx in _STRIP:
        text = rx.sub(blank, text)
    return _DYNAMIC.sub("import()", text)


def code_only(text: str) -> str:
    """Comments and one-line string literals blanked (skill_packages' own
    rules): what is left is what the code REFERENCES."""
    import skill_packages as SP
    return SP._COMMENT.sub(" ", SP._STRING.sub(" ", text))


def identifiers(text: str) -> list[str]:
    """The code-shaped identifiers the code uses (skill_classify.code_shaped:
    the rule the tag stage verifies a skill's topics with)."""
    import skill_classify
    return sorted({n for n in _ID.findall(code_only(text))
                   if skill_classify.code_shaped(n)})


def specifiers(text: str) -> list[str]:
    return sorted(set(_SPEC.findall(text)))


_BUILTINS: set | None = None


def node_builtins() -> set[str]:
    """Node's own modules (`fs`, `path`), read from the @types/node the
    detector already reads (`declare module "fs"`); empty when absent."""
    global _BUILTINS
    if _BUILTINS is None:
        import glob
        import skill_packages as SP
        out: set[str] = set()
        for p in glob.glob(os.path.join(SP.NODE_TYPES, "*.d.ts")):
            try:
                with open(p, encoding="utf-8", errors="replace") as f:
                    out |= set(re.findall(r"""declare\s+module\s+['"]"""
                                          r"""(?:node:)?([\w/]+)['"]""",
                                          f.read()))
            except OSError:
                pass
        _BUILTINS = out
    return _BUILTINS


def file_facts(text: str) -> dict:
    """{imports {binding: module}, packages [held], bindings {binding:
    held package}, unheld [npm names], specifiers, identifiers} of one
    file, from its own imports (skill_packages.imported_names and
    package_of_specifier: `three/tsl`, `three/webgpu` -> TSL)."""
    import skill_packages as SP
    msgs = [{"role": "user", "content": text}]
    imports = SP.imported_names(msgs)
    specs = specifiers(text)
    held, unheld = set(), set()
    for s in specs:
        p = SP.package_of_specifier(s)
        if p:
            held.add(p)
            continue
        if s.startswith((".", "/", "node:", "#", "~")) or ":" in s:
            continue
        name = _deps().package_of(s)
        if not _NPM_NAME.fullmatch(name) or name in node_builtins():
            continue
        unheld.add(name)
    bindings = {}
    for b, mod in imports.items():
        p = SP.package_of_specifier(mod)
        if p:
            bindings[b] = p
    return {"imports": imports, "packages": sorted(held),
            "bindings": bindings, "unheld": sorted(unheld),
            "specifiers": specs,
            "identifiers": identifiers(strip_imports(text))}


def is_generated(text: str) -> bool:
    m = _LEADING_COMMENT.match(text or "")
    return bool(m and _GENERATED.search(m.group(0)))


def screen(text: str) -> tuple[str, str | None, dict | None]:
    """(text with zero-width typography stripped, the drop reason or None,
    the typography NOTE or None) -- skill_screen's rules applied to code."""
    import skill_screen as S
    text, note = S.strip_typography(text)
    kinds = sorted({k for k in (S._invisible_kind(ch) for ch in text) if k})
    if kinds:
        return text, "hidden_characters: " + ", ".join(kinds), note
    for rx, why in S._CRED[S._CRED_PROSE_ONLY:]:
        if rx.search(text):
            return text, f"credential: {why}", note
    return text, None, note


# ---------------------------------------------------------------------------
# Discovery.
# ---------------------------------------------------------------------------
def roots_of(tree: dict, linked_dirs=()) -> list[dict]:
    """The examples roots: the linked directories first, then the outermost
    directory named in EXAMPLE_DIRS on every blob's path."""
    blobs = [e["path"] for e in (tree or {}).get("entries") or []
             if e.get("type") == "blob" and e.get("path")]
    names = {n.lower() for n in EXAMPLE_DIRS}
    out: dict[str, dict] = {}
    for d in linked_dirs or ():
        d = str(d or "").strip("/")
        if d and d not in out:
            out[d] = {"path": d, "why": "linked by the prompt", "files": 0}
    linked = list(out)
    for p in blobs:
        if any(p == d or p.startswith(d + "/") for d in linked):
            continue
        parts = p.split("/")[:-1]
        for i, part in enumerate(parts):
            if part == "node_modules":
                break
            if part.lower() in names:
                r = "/".join(parts[:i + 1])
                out.setdefault(r, {"path": r, "why": f"the directory name "
                                   f"'{part}' marks examples", "files": 0})
                break
    return list(out.values())


def root_of(path: str, roots: list[dict]) -> str | None:
    for r in roots:
        if path.startswith(r["path"] + "/"):
            return r["path"]
    return None


def group_of(path: str, root: str) -> str:
    rel = path[len(root) + 1:]
    return f"{root}/{rel.split('/', 1)[0]}" if "/" in rel else path


def _safe_parts(path: str) -> list[str] | None:
    parts = path.split("/")
    if not path or path.startswith("/") or any(
            p in ("", ".", "..") or ":" in p or "\\" in p for p in parts):
        return None
    return parts


def _pre_filter(path: str, root: str, size) -> str | None:
    parts = path.split("/")
    if "node_modules" in parts:
        return "node_modules"
    below = path[len(root) + 1:].split("/")[:-1]
    if any(p in _deps().BUILT_DIRS for p in below):
        return "built_dir"
    base = parts[-1]
    if base in LOCKFILES:
        return "lockfile"
    if not base.lower().endswith(EXTS):
        return "extension"
    if ".min." in base.lower():
        return "minified"
    if _safe_parts(path) is None:
        return "unsafe_path"
    if isinstance(size, int) and size > _deps().MAX_FILE_BYTES:
        return "too_large"
    return None


def _ext_of(path: str) -> str:
    base = path.rsplit("/", 1)[-1]
    return os.path.splitext(base)[1].lower() or "(none)"


# ---------------------------------------------------------------------------
# The blob cache.
# ---------------------------------------------------------------------------
def _read_json(path: str, default):
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    except (OSError, ValueError):
        return default


def _write_atomic(path: str, data: bytes) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = f"{path}.{os.getpid()}.tmp"
    with open(tmp, "wb") as f:
        f.write(data)
    os.replace(tmp, path)


def stored_path(row: dict) -> str | None:
    """The stored text of a manifest row, or None."""
    parts = _safe_parts(row.get("path") or "")
    if parts is None or not row.get("store"):
        return None
    return os.path.join(store_root(), row["store"], *parts)


def read_stored(row: dict) -> str | None:
    p = stored_path(row)
    if not p:
        return None
    try:
        with open(p, encoding="utf-8") as f:
            return f.read()
    except (OSError, UnicodeDecodeError):
        return None


# ---------------------------------------------------------------------------
# The stage.
# ---------------------------------------------------------------------------
def collect(did: str, pkg: dict | None, tree: dict | None, *,
            linked_dirs=(), beat=None) -> dict:
    """Discover, fetch, filter, screen and label one onboarding's example
    files; write examples.json and examples/manifest.jsonl. Returns the
    counts the stage records: example_groups, example_files,
    example_dropped, per_package (and skipped when it does not apply)."""
    import onboarding
    import package_net as net
    beat = beat or (lambda s: None)
    why = None
    if not pkg:
        why = "no package"
    elif pkg.get("ecosystem") != "npm":
        why = f"not supported for {pkg.get('ecosystem')}: JS/TS packages only"
    elif not pkg.get("commit"):
        why = ("no commit for this version: examples are read at a commit "
               "only (the tarball ships no example directories to trust)")
    elif not (pkg.get("repository") or {}).get("owner"):
        why = "no GitHub repository recorded for the package"
    elif not tree or not isinstance(tree.get("entries"), list):
        why = "no tree listing at the commit" + (
            f" ({tree.get('error')})" if tree and tree.get("error") else "")
    elif tree.get("error") and not tree.get("entries"):
        why = f"the tree listing failed: {tree['error']}"
    if why:
        onboarding.write_json(did, SUMMARY, {"skipped": why, "at": time.time()})
        return {"skipped": why, "example_groups": 0, "example_files": 0,
                "example_dropped": 0, "per_package": {}}
    gh = pkg["repository"]
    owner, repo, commit = gh["owner"], gh["repo"], pkg["commit"]
    repository = f"{owner}/{repo}"
    name, version = pkg["name"], pkg["version"]
    sdir = store_dir(name, version, commit)
    store_key = "/".join((_deps().slug(name, version), commit))
    blobs_path = os.path.join(sdir, BLOBS)
    blobs = _read_json(blobs_path, {})
    roots = roots_of(tree, linked_dirs)
    dropped: list[dict] = []
    by_ext: collections.Counter = collections.Counter()
    cand: list[dict] = []
    for e in tree.get("entries") or []:
        if e.get("type") != "blob" or not e.get("path"):
            continue
        r = root_of(e["path"], roots)
        if r is None:
            continue
        reason = _pre_filter(e["path"], r, e.get("size"))
        if reason == "extension":
            by_ext[_ext_of(e["path"])] += 1
            continue
        if reason:
            dropped.append({"path": e["path"], "reason": reason})
            continue
        cand.append({"path": e["path"], "root": r, "sha": e.get("sha"),
                     "size": e.get("size")})
    cand.sort(key=lambda c: c["path"])
    fetched = reused = bytes_fetched = 0
    typo_files = typo_chars = 0
    texts: dict[str, str] = {}
    for i, c in enumerate(cand):
        beat(f"examples: {i + 1}/{len(cand)} {c['path'][-120:]}")
        sha = c.get("sha")
        known = blobs.get(sha) if sha else None
        if known and known.get("rules") == RULES_VERSION:
            if known.get("verdict") != "kept":
                dropped.append({"path": c["path"],
                                "reason": known["verdict"]})
                reused += 1
                continue
            src = os.path.join(sdir, *known["path"].split("/"))
            try:
                with open(src, encoding="utf-8") as f:
                    txt = f.read()
            except (OSError, UnicodeDecodeError):
                txt = None
            if txt is not None and hashlib.sha256(txt.encode(
                    "utf-8")).hexdigest() == known.get("text_sha256"):
                if known["path"] != c["path"]:
                    _write_atomic(os.path.join(sdir, *c["path"].split("/")),
                                  txt.encode("utf-8"))
                texts[c["path"]] = txt
                typo_files += bool(known.get("typography"))
                typo_chars += int(known.get("typography") or 0)
                reused += 1
                continue
        try:
            resp = net.raw(owner, repo, commit, c["path"],
                           max_bytes=_deps().MAX_FILE_BYTES)
        except net.TooLarge:
            dropped.append({"path": c["path"], "reason": "too_large"})
            continue
        if resp.status == 404:
            dropped.append({"path": c["path"], "reason": "not found (404)"})
            continue
        if resp.status != 200:
            import worker
            raise RuntimeError(worker.describe(
                f"{c['path']}: HTTP {resp.status} from "
                "raw.githubusercontent.com", True,
                "retried automatically; files already stored are not "
                "fetched again", "worker"))
        data = resp.body
        fetched += 1
        bytes_fetched += len(data)
        verdict, txt, typo = _judge(c["path"], data, sha)
        if sha:
            blobs[sha] = {"verdict": verdict, "rules": RULES_VERSION,
                          "path": c["path"], "bytes": len(data)}
        if verdict != "kept":
            dropped.append({"path": c["path"], "reason": verdict})
            continue
        _write_atomic(os.path.join(sdir, *c["path"].split("/")),
                      txt.encode("utf-8"))
        if sha:
            blobs[sha].update(text_sha256=hashlib.sha256(
                txt.encode("utf-8")).hexdigest(), typography=typo)
        typo_files += bool(typo)
        typo_chars += typo
        texts[c["path"]] = txt
    if blobs:
        _write_atomic(blobs_path, json.dumps(blobs, indent=0, sort_keys=True)
                      .encode("utf-8"))
    # Near-duplicates: deps._dedupe's rule over what survived.
    keep = set(_deps()._dedupe(sorted(texts), texts, ranked=True))
    for p in sorted(texts):
        if p not in keep:
            dropped.append({"path": p, "reason": "duplicate"})
    by_path = {c["path"]: c for c in cand}
    rows = []
    groups: dict[str, set] = collections.defaultdict(set)
    per_pkg: dict[str, dict] = collections.defaultdict(
        lambda: {"files": 0, "groups": set()})
    unheld: dict[str, dict] = collections.defaultdict(
        lambda: {"files": 0, "groups": set()})
    for p in sorted(keep):
        c = by_path[p]
        txt = texts[p]
        facts = file_facts(txt)
        g = group_of(p, c["root"])
        gh_ = group_hash(repository, g)
        rows.append({"id": file_id(repository, p, c.get("sha") or ""),
                     "repository": repository, "commit": commit,
                     "package": f"{name}@{version}", "root": c["root"],
                     "group": g, "group_hash": gh_, "path": p,
                     "blob": c.get("sha"),
                     "bytes": len(txt.encode("utf-8")), "store": store_key,
                     "imports": facts["imports"],
                     "packages": facts["packages"],
                     "unheld": facts["unheld"],
                     "identifiers": facts["identifiers"]})
        groups[g].add(p)
        for r in roots:
            if r["path"] == c["root"]:
                r["files"] += 1
        for pk in facts["packages"]:
            per_pkg[pk]["files"] += 1
            per_pkg[pk]["groups"].add(g)
        for u in facts["unheld"]:
            unheld[u]["files"] += 1
            unheld[u]["groups"].add(g)
    lines = "".join(json.dumps(r, sort_keys=True) + "\n" for r in rows)
    mp = os.path.join(onboarding.out_dir(did), MANIFEST)
    _write_atomic(mp, lines.encode("utf-8"))
    counts = collections.Counter(d["reason"].split(":")[0] for d in dropped)
    if by_ext:
        counts["extension"] = sum(by_ext.values())
    top_dirs = sorted({e["path"].split("/")[0] for e in tree.get("entries")
                       or [] if e.get("type") == "tree"
                       and "/" not in e.get("path", "")})
    per_package = {k: {"files": v["files"], "groups": len(v["groups"])}
                   for k, v in sorted(per_pkg.items())}
    summary = {
        "package": f"{name}@{version}", "repository": repository,
        "commit": commit, "rules": RULES_VERSION,
        "example_dir_names": list(EXAMPLE_DIRS),
        "roots": roots,
        "tree": {"entries": len(tree.get("entries") or []),
                 "truncated": bool(tree.get("truncated")),
                 "walked": tree.get("walked") or [],
                 "top_dirs": top_dirs},
        "groups": len(groups), "files": len(rows),
        "files_by_group": {g: len(v) for g, v in sorted(groups.items())},
        "chunks": None,
        "chunks_why": "chunked by the knn stage (example_knn.build)",
        "per_package": per_package,
        "dropped": dict(sorted(counts.items())),
        "dropped_files": sorted(dropped, key=lambda d: d["path"]),
        "dropped_extensions": dict(sorted(by_ext.items())),
        # The "onboard next" list (7.3): imports of packages we do not hold,
        # by the number of groups that use them.
        "unheld": sorted(({"package": k, "groups": len(v["groups"]),
                           "files": v["files"]} for k, v in unheld.items()),
                         key=lambda x: (-x["groups"], -x["files"],
                                        x["package"])),
        "fetched": fetched, "reused": reused,
        "bytes_fetched": bytes_fetched,
        "bytes_kept": sum(r["bytes"] for r in rows),
        "screen": {"typography_stripped_files": typo_files,
                   "typography_stripped_chars": typo_chars},
        "manifest_sha256": hashlib.sha256(lines.encode("utf-8")).hexdigest(),
        "at": time.time()}
    onboarding.write_json(did, SUMMARY, summary)
    return {"example_groups": len(groups), "example_files": len(rows),
            "example_dropped": sum(counts.values()),
            "per_package": per_package, "bytes_fetched": bytes_fetched,
            "roots": [r["path"] for r in roots],
            "unheld": [u["package"] for u in summary["unheld"]]}


def _judge(path: str, data: bytes, sha: str | None
           ) -> tuple[str, str | None, int]:
    """(verdict: "kept" or the drop reason, the stored text, typography
    characters stripped)."""
    if sha and git_blob_sha(data) != sha:
        return "blob_mismatch", None, 0
    if b"\0" in data:
        return "binary", None, 0
    try:
        txt = data.decode("utf-8")
    except UnicodeDecodeError:
        return "not_utf8", None, 0
    if is_generated(txt):
        return "generated", None, 0
    if _deps().is_minified(path, txt):
        return "minified", None, 0
    txt, reason, note = screen(txt)
    if reason:
        return reason, None, 0
    return "kept", txt, int((note or {}).get("stripped") or 0)


# ---------------------------------------------------------------------------
# Reading the manifests back (example_knn, package_eval).
# ---------------------------------------------------------------------------
def manifest_rows(did: str) -> list[dict]:
    import onboarding
    p = os.path.join(onboarding.out_dir(did), MANIFEST)
    out = []
    try:
        with open(p, encoding="utf-8") as f:
            for ln in f:
                ln = ln.strip()
                if ln:
                    out.append(json.loads(ln))
    except (OSError, ValueError):
        return []
    return out


def manifests() -> list[tuple[str, str]]:
    """[(onboarding id, manifest path)] for every onboarding with one."""
    import onboarding
    root = onboarding.root()
    out = []
    try:
        names = sorted(os.listdir(root))
    except OSError:
        return []
    for did in names:
        p = os.path.join(root, did, MANIFEST)
        if os.path.isfile(p):
            out.append((did, p))
    return out


def manifest_sha256(did: str) -> str | None:
    import onboarding
    try:
        with open(os.path.join(onboarding.out_dir(did), MANIFEST), "rb") as f:
            return hashlib.sha256(f.read()).hexdigest()
    except OSError:
        return None


if __name__ == "__main__":
    if len(sys.argv) >= 3 and sys.argv[1] == "show":
        import onboarding
        print(json.dumps(onboarding.read_json(sys.argv[2], SUMMARY),
                         indent=1))
    else:
        print(__doc__)
